<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php if ($crumbs && is_array($crumbs)) : ?>
<div class="breadcrumbs">
	<div class="container">
		<?php 
			$pagecrumbsTitle = $block->getLayout()->getBlock('page.main.title');
			if($pagecrumbsTitle){
				$pagecrumbsTitle = $pagecrumbsTitle->getPageTitle();
				if(!trim($pagecrumbsTitle)){
					$pagecrumbsTitle = $block->getLayout()->createBlock('Magento\Theme\Block\Html\Title')->getPageTitle();
				}
			}
		?>
		<h2 class="pagecrumbs-title"><?php echo $pagecrumbsTitle;?></h2>
		<ul class="items">
			<?php foreach ($crumbs as $crumbName => $crumbInfo) : ?>
				<li class="item <?php /* @escapeNotVerified */ echo $crumbName ?>">
				<?php if ($crumbInfo['link']) : ?>
					<a href="<?php /* @escapeNotVerified */ echo $crumbInfo['link'] ?>" title="<?php echo $block->escapeHtml($crumbInfo['title']) ?>">
						<?php echo $block->escapeHtml($crumbInfo['label']) ?>
					</a>
				<?php elseif ($crumbInfo['last']) : ?>
					<strong><?php echo $block->escapeHtml($crumbInfo['label']) ?></strong>
				<?php else: ?>
					<?php echo $block->escapeHtml($crumbInfo['label']) ?>
				<?php endif; ?>
				</li>
			<?php endforeach; ?>
		</ul>
	</div>
</div>
<?php endif; ?>
