<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */


?>
<div class="footer-copyright">
	<div class="main1">
		<small class="copyright">
			<span><?php /* @escapeNotVerified */ echo preg_replace('/yyyy/', date('Y'), $block->getCopyright()); ?></span>
		</small>
	</div>
	<?php 
    	echo $block->getLayout()
       ->createBlock('Magento\Cms\Block\Block')
       ->setBlockId('block-footer-menu')
       ->toHtml();
	?>
	
</div>