<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$media = $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA)."images/rod.jpg";
?>
<div class="contact-container">
                                <h6 class="content-title contact-title">This tool helps you determine the outer diameter of your finished roll of stretch film!</h6>
                                <p>Just enter the length of the material in feet, the thickness of the material in gauge, and the outer diameter of the core in inches.</p>
                                <p><u>Sample Equation:</u> CHF1880A - Length of Material = 1,500', Thickness of Material = 80ga, OD of the Core = 3.375"<br/>So the outer diameter of the finished roll will be = 5.45"<br><br></p>
                                <div class="row">
                                    <div class="col-lg-12 mb-5" style="text-align: center;">
                                        <img style="width:400px" src="<?php echo $media;?>">
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-lg-12">
                                        <!-- contact form -->
                                        <div class="waituk_contact-form">
                                            <div class="row">
                                                <div class="col-md-4">
                                                    <div class="form-group">
                                                        <label for="Length of Material">Length of Material <span style="color:red">*</span></label>
                                                        <input type="number" name="" id="var1" class="form-control" >
                                                    </div>
                                                </div>
                                                <div class="col-md-4">
                                                    <div class="form-group">
                                                        <label for="Thickness of Material">Thickness of Material <span style="color:red">*</span></label>
                                                        <input type="number" name="" id="var2" class="form-control" >
                                                    </div>
                                                </div>
                                                <div class="col-md-4">
                                                    <div class="form-group">
                                                        <label for="OD of Core">OD of Core <span style="color:red">*</span></label>
                                                        <input type="number" name="" id="var3" class="form-control" >
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="row">
                                                <div class="col-md-12">
                                                    <div class="btn-container" style="text-align: center;">
                                                        <button onclick="calculate()" class="btn btn-primary btn-arrow">Calculate</button>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-lg-12 mt-5">
                                        <div id="result"></div>
                                    </div>
                                </div>
                            </div>
                            <script>
                        function calculate() {
                          var var1 = document.getElementById("var1").value;
                          var var2 = document.getElementById("var2").value;
                          var var3 = document.getElementById("var3").value;
                          if(var1!='' && var2!='' && var3!='') {  
                            function formatResult(result) {
                                return result.toFixed(2);
                            }
                              // Solve the equation here
                              var result =  2 * Math.sqrt(((var1 * 12 * var2 / (3.14159265358979 * 100000)) + ((var3 * var3) / 4)));
                              var result = formatResult(result);
                          //alert(result);

                          document.getElementById("result").innerHTML = "<h6 class='content-title contact-title'>OD of the Finished Roll is <span style='color: #007fff'>"+result+" Inches</span></h6>";
                      } else {
                            alert('Please enter correct dimensions.');
                          }
                        }
                      </script>