<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * Product media data template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Gallery
 */
?>
<?php
$_aloHelper = $this->helper('Magiccart\Alothemes\Helper\Data');
$_product   = $block->getProduct();
$product_label = $_aloHelper->getLabels($_product); 
echo $product_label ? '<div class="product-label">' . $product_label . '</div>' : ''; 
?>
<?php
    $gallery  = json_decode( $block->getGalleryImagesJson(), true );
?>
<div class="gallery-placeholder" data-gallery-role="gallery-placeholder">
    <div class="gallery-items">
        <?php foreach ($gallery as $shot) : ?>
            <div class="fotorama__stage">
                <div class="fotorama__active">
                    <img src="<?php echo $shot['img'] ?>"  data-src="<?php echo $shot['full'] ?>" alt="<?php echo $shot['caption'] ?>">
                </div>                
            </div>
        <?php endforeach ?>
    </div>
</div>
<script type="text/javascript">
    require([
        'jquery',
        'magiccart/slick',
        'magiccart/sticky',
        'mage/mage',
        'domReady!'
        ], function($, slick, zoom){
            $( document ).ready(function($) {
                if($(window).width() > 767){
                    $('.product-shop-content').stick_in_parent({
                        offset_top: 50
                    });
                }
            });            
    });
</script>