<?php 
    $product = $block->getProduct();
    $show_size = false;
    if ($product->getTypeId() == \Magento\ConfigurableProduct\Model\Product\Type\Configurable::TYPE_CODE) {
        
        $data = $product->getTypeInstance()->getConfigurableOptions($product);
        $show_size = false;
        foreach ($data as $key => $value) {
            if($value['0']['attribute_code'] == 'size')
            {
                $show_size = true;
                break;
            }
        }        
    }
    if (!$show_size) return;
    $sizeguideBlock = $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('size_guide')->toHtml();
 ?>

<div class="size-guide">
    <a class="size-guide-text" ><?php echo $block->escapeHtml(__('Size Guide')); ?></a>
    <div id="size-guide-popup" style="display: none;"><?php echo $sizeguideBlock; ?></div>
</div>
<script type="text/javascript">
    require([
    "jquery",
    'Magento_Ui/js/modal/modal'
    ], function ($, modal) {
        $('.size-guide .size-guide-text').click(function () {
            $('#size-guide-popup').modal({
                type: 'popup',
                modalClass: 'modals-sizeguide',
                responsive: true, 
                buttons: false           
            });
            $("#size-guide-popup").modal("openModal");
        });
    });
</script>