<?php
/**
 * Copyright © 2015 Ihor Vansach (ihor@magefan.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog sidebar recent posts template
 *
 * @var $block \Magefan\Blog\Block\Sidebar\Recent
 */
?>

<?php
	$_postCollection = $block->getPostCollection();
    $maxWidth  = 370;
    $maxHeight = 247;
?>
<?php if (!$_postCollection->count()) return ?>
<div class="widget block-recent-posts" data-bind="scope: 'recent-posts'">
    <div class="block-title">
        <strong><?php echo __($this->getTitle()) ?></strong>
    </div>
    <div class="block-content magicblog magicslider autoplay"
    <?php foreach ($this->getFrontendCfg() as $opt) :?>
        data-<?php echo $opt ?>='<?php echo $this->getData($opt) ?>'
    <?php endforeach;?>     
    >
    	<?php foreach ($_postCollection as $_post) { ?>
            <?php $_postUrl = $_post->getPostUrl(); ?>
            <?php $_postName = $block->escapeHtml($_post->getTitle()) ?>
            <div class="item">
                <div class="post-description clearfix">
                    <?php if ($featuredImage = $_post->getFeaturedImage()) { ?>
                    <div class="post-ftimg-hld blog-image al-style-2 image-container">
                        <a href="<?php echo $_postUrl ?>" title="<?php echo $_postName ?>">
                            <img class="img-blog" src="<?php /* @escapeNotVerified */ echo $featuredImage ?>" alt="<?php echo $_postName ?>"  max-width="<?= /* @escapeNotVerified */ $maxWidth ?>px" max-height="<?= /* @escapeNotVerified */ $maxHeight ?>px" />
                        </a>
                    </div>
                    <?php } ?>
					<div class="blog_short_text clearfix">
						<div class="post-info clear">
                            <div class="content-inner">
    							<a class="post-item-link" href="<?php echo $_post->getPostUrl() ?>">
    								<?php echo $_postName ?>
    							</a>
                                <div class="post-meta">
                                    <div class="item post-posed-date">
                                        <span class="label"><em class="fa fa-calendar"></em></span>
                                        <span class="value"><?php echo $block->getPostedOn($_post, 'd M, Y') //'F d, Y' ?></span>
                                    </div>
                                    <?php if($_post->getAuthor()) : ?>
                                            <div class="item post-author">
                                            <span class="label"><em class="fa fa-user"></em></span>
                                            <?php echo __('Posted by:'); ?>
                                            <a href="#"><?php echo $_post->getAuthor()->getName() ?></a>
                                        </div>
                                    <?php endif ?>
                                </div>
                                <div class="post-text-hld shortcontent-text clearfix">
                                    <?php echo $block->getShorContent($_post) ?>
                                </div>
    							<a class="post-read-more" href="<?php echo $_postUrl ?>" title="<?php echo $_postName ?>">
    							   <?php echo __('Read more') ?>
    							</a>
                            </div>
						</div>
					</div>
                    
                </div>
                
            </div>

        <?php } ?>
    </div>
    <div class="post action">
    	<a href="<?php echo $this->getUrl('blog') ?>" class="button-o"><?php echo __('View more') ?></a>
    </div>
</div>
