<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Category view template
 *
 * @var $block \Magento\Catalog\Block\Category\View
 */
?>
<?php
    $_helper    = $this->helper('Magento\Catalog\Helper\Output');
    $_category  = $block->getCurrentCategory();
    $_imgHtml   = '';
    if(!$_category) return;
    if ($_imgUrl = $_category->getImageUrl()) {
?>
<style> .catalog-category-view .breadcrumbs{background-image: url('<?php echo $_imgUrl ?>');} </style>
<?php
    }
?>