<?php
if(!$this->getEnabled()) return;
$selector = 'alo-content-'.uniqid();
$testimonials = $this->getTestimonials();
if(!count($testimonials)) return;
?>
<div class="<?php /* @escapeNotVerified */ echo $selector ?>" data-mage-init='{"gridSlider": {}}' >
   <div class="block-testimonial">
        <?php echo $this->getTitle() ? '<h3 class="block-title title item">' . '<span>' . $this->escapeHtml($this->getTitle()) . '</span>' . '</h3>' : '' ?>
	</div>
   <div class="block-content">
		<div class="testimonial grid-slider"
			data-fade='true'
		<?php foreach ($this->getFrontendCfg() as $opt) :?>
			data-<?php /* @escapeNotVerified */ echo $opt ?>='<?php /* @escapeNotVerified */ echo $this->getData($opt) ?>'
		<?php endforeach;?>  
		>
			<?php $i=0; foreach ($testimonials as $testimonial) :?>
				<div class="item">
					<div class="inner-customer clearfix">
						<div class="inner-left">
							<div class="customer">
								<a href="<?php echo $this->getUrl('testimonial'); ?>">
									<img class="avatar img-responsive" src="<?php echo $this->escapeUrl($this->getImage($testimonial)) ?>" alt="<?php echo __($this->escapeHtml($testimonial->getName())) ?>" title="<?php echo __($this->escapeHtml($testimonial->getName())) ?>" />
								</a>
							</div>
						</div>
						<div class="inner-right">
							<p class="name title-name"><?php echo $this->escapeHtml($testimonial->getName()); ?></p>
						</div>
					</div>
					 <div class="testimonial_text">
						<div class="content sub-text"><?php echo $this->escapeHtml($testimonial->getText()); ?></div>
					</div>
				</div>
			<?php endforeach ?>
		</div>
	</div>
</div>
